# Numpy 玩耍

In [1]:
import numpy as np 

In [2]:
normal_lst = range(1000)
%timeit [i**2 for i in normal_lst]

1000 loops, best of 3: 493 µs per loop


In [3]:
np_lst = np.arange(1000)
%timeit np_lst**2

The slowest run took 14.52 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.31 µs per loop


In [6]:
np_lst = np.ones(5)*3

In [8]:
normal_lst = [1,1,1,1,]*3
print(normal_lst, len(normal_lst))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] 12


In [9]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [10]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [11]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [12]:
np.empty((2,3,3))

array([[[  6.23042070e-307,   3.56043053e-307,   1.60219306e-306],
        [  2.44763557e-307,   1.69119330e-306,   7.56599807e-307],
        [  8.90104239e-307,   1.24610383e-306,   1.69118108e-306]],

       [[  8.06632139e-308,   1.20160711e-306,   1.69119330e-306],
        [  1.29062229e-306,   1.24610383e-306,   1.24610723e-306],
        [  6.89805151e-307,   1.78020169e-306,   1.42410974e-306]]])

In [14]:
np.ones_like(np_lst)

array([ 1.,  1.,  1.,  1.,  1.])

In [15]:
np.zeros_like(np_lst)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.linspace(0,1,10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [17]:
stock_cnt = 200
view_days = 504
stock_day_change = np.random.standard_normal((stock_cnt,view_days))

In [21]:
print(stock_day_change.shape)

(200, 504)


In [22]:
np.around(stock_day_change[:2,:5], 2)

array([[ 1.38,  0.18,  0.21, -0.54, -0.11],
       [-0.41, -1.2 , -0.1 , -1.51,  0.12]])

In [23]:
tmp_test = stock_day_change[:2,:5].copy()
tmp_test[0][0] = np.nan

In [24]:
tmp_test

array([[        nan,  0.18058772,  0.21211613, -0.5359009 , -0.11450511],
       [-0.41155034, -1.19898536, -0.09969371, -1.50525033,  0.12189656]])

In [27]:
mask = stock_day_change[:2,:5] >0.5

In [28]:
print(mask)

[[ True False False False False]
 [False False False False False]]


In [34]:
tmp_test = stock_day_change[-2:,-5:]
tmp_test[(tmp_test > 1) |(tmp_test < -1)]

array([ 1.42136492,  1.10979337,  1.24257737, -1.68384141])

In [37]:
np.all(stock_day_change[:2,:5]>0)

False

In [38]:
np.any(stock_day_change[:2,:5]>0)

True

In [43]:
stock_day_change.shape

(200, 504)

In [47]:
print('np1:',stock_day_change[:2,:5])
print('np2:',stock_day_change[-2:,-5:])
np.maximum(stock_day_change[:2,:5],stock_day_change[-2:,-5:])

np1: [[ 1.38000455  0.18058772  0.21211613 -0.5359009  -0.11450511]
 [-0.41155034 -1.19898536 -0.09969371 -1.50525033  0.12189656]]
np2: [[-0.84537274  0.15707293  1.42136492  1.10979337  0.95895085]
 [-0.2670522   0.88268425 -0.53953648  1.24257737 -1.68384141]]


array([[ 1.38000455,  0.18058772,  1.42136492,  1.10979337,  0.95895085],
       [-0.2670522 ,  0.88268425, -0.09969371,  1.24257737,  0.12189656]])

In [49]:
change_int = stock_day_change[:2,:5].astype(int)
print(change_int)

[[ 1  0  0  0  0]
 [ 0 -1  0 -1  0]]


In [50]:
np.diff(stock_day_change[:2,:5])

array([[-1.19941682,  0.03152841, -0.74801703,  0.42139579],
       [-0.78743503,  1.09929166, -1.40555662,  1.62714689]])

In [51]:
np.diff(stock_day_change[:2,:5],axis=0)

array([[-1.79155488, -1.37957309, -0.31180984, -0.96934943,  0.23640167]])

In [52]:
tmp_test 

array([[-0.84537274,  0.15707293,  1.42136492,  1.10979337,  0.95895085],
       [-0.2670522 ,  0.88268425, -0.53953648,  1.24257737, -1.68384141]])

In [53]:
np.where(tmp_test>0, 1, 0)

array([[0, 1, 1, 1, 1],
       [0, 1, 0, 1, 0]])

In [54]:
np.where(np.logical_and(tmp_test>0.5, tmp_test<1),1,0)

array([[0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0]])

In [55]:
np.save('filename',tmp_test)
np.load('filename.npy')

array([[-0.84537274,  0.15707293,  1.42136492,  1.10979337,  0.95895085],
       [-0.2670522 ,  0.88268425, -0.53953648,  1.24257737, -1.68384141]])

# 統計值

In [56]:
stock_day_change_four = stock_day_change[:4,:4]
stock_day_change_four

array([[ 1.38000455,  0.18058772,  0.21211613, -0.5359009 ],
       [-0.41155034, -1.19898536, -0.09969371, -1.50525033],
       [ 0.71869765,  0.12929549, -0.63355098,  0.75579835],
       [ 1.36273151, -0.76876048, -0.32114841, -1.62665736]])

In [60]:
print('4天內最大漲幅',np.max(stock_day_change_four,axis=1))
print('4天內最小漲幅',np.min(stock_day_change_four,axis=1))
print('4天內平均漲跌',np.mean(stock_day_change_four,axis=1))
print('4天內振幅幅度',np.max(stock_day_change_four,axis=1))

4天內最大漲幅 [ 1.38000455 -0.09969371  0.75579835  1.36273151]
4天內最小漲幅 [-0.5359009  -1.50525033 -0.63355098 -1.62665736]
4天內平均漲跌 [ 0.30920187 -0.80386994  0.24256013 -0.33845868]
4天內振幅幅度 [ 1.38000455 -0.09969371  0.75579835  1.36273151]


In [66]:
np.random.normal(loc=100,scale=50,size=(100,1))

array([[  71.78655616],
       [  60.70527614],
       [  62.23394214],
       [ 117.95850201],
       [ 170.20984897],
       [ 155.88556454],
       [ 166.84969783],
       [ 150.34761762],
       [  75.81681305],
       [ 116.24421177],
       [ 109.16673989],
       [ 103.89917094],
       [ 155.54125118],
       [  75.75197166],
       [ 194.14102525],
       [ 139.38671267],
       [  99.93575617],
       [  97.49820506],
       [ 131.39713066],
       [ 102.41104075],
       [ 114.03946321],
       [ 143.92327719],
       [  86.25752105],
       [  90.21176338],
       [ 101.02644491],
       [ 124.97580356],
       [ 210.84533898],
       [ 175.90559395],
       [  78.66059287],
       [ 110.88257029],
       [ 225.49521058],
       [  59.51827685],
       [ 144.41017633],
       [ 104.49646323],
       [  47.30002994],
       [ 131.74323208],
       [ 166.99441192],
       [ 108.36692934],
       [ 136.09252885],
       [  66.16444971],
       [  94.88776463],
       [ 117.728